server:
    port: 9191
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sita
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true

app:
  source: C:/Training/input?fileName=Test_Camel.txt
  destination: C:/Training/output/